### ISSUE TITLE
Error when swipe in movile devices

### ISSUE THREAD

**Issue by liongoncalves** [snake-345/jcarouselSwipe#2]
Hey, i just found a little bug when swiping in mobile devices. The problem is caused because you use event.touches instead of event.changedTouches, and in mobile devices that causes an error at the touchend or touchcancel events. If you changed that it works great. 

Great plugin by the way. 

Thanks dude =).

**Comment by snake-345** [comment]
On what device you find this bug?

**Comment by liongoncalves** [comment]
On almost every device in fact if you use chrome developer tools and put the browser in Mobile mode you can see it

**Comment by snake-345** [comment]
Oh, i'm broke it with past release) Will need write some auto tests in future) 
Fixed. 
https://github.com/snake-345/jcarouselSwipe/releases/tag/0.3.2

**Comment by liongoncalves** [comment]
Awesome dude thanks!. 

And again great plugin =).
