### ISSUE TITLE
The Swipe not working when dealing with RTL

### ISSUE THREAD

**Issue by maenabbasi** [snake-345/jcarouselSwipe#6]
$('.jcarousel')
            .jcarousel({
                // Options go here
				horizontalDirection:'rtl'
				,rtl:true
            }).jcarouselSwipe();
when trying this, it is not working and the content disappear

**Comment by snake-345** [comment]
Can you try set rtl to jcarousel without jcarouselSwipe plugin. I think problem in jcarousel.

**Comment by maenabbasi** [comment]
```
(function($) {
    $(function() {
        /*
        Carousel initialization
        */
        $('.jcarousel')
            .jcarousel({
                // Options go here
				horizontalDirection:'rtl'
				,rtl:true
            }).jcarouselSwipe();
		$('.jcarousel').jcarouselSwipe({
			draggable: false ,
		});
        
    });
})(jQuery);
```
Apply the code above, it works now but when I swipe right it scroll to opposite left 
[https://jsfiddle.net/t3nbp292/](url)

**Comment by snake-345** [comment]
Ok. I see. I will fix this. Thanks for the issue and example)

**Comment by snake-345** [comment]
Hi. Sorry for waiting. I fixed this issue. You can check it [here](https://jsfiddle.net/t3nbp292/2/)
