### ISSUE TITLE
How to change the touch sensitivity?

### ISSUE THREAD

**Issue by diegosomar** [snake-345/jcarouselSwipe#8]
Hello! I'm using this great plugin and works fine. In some case, when we scroll the page on mobile and the finger goes over JCarousel area, the event swipe is handled and the carousel slides.

But it occours in accidental uses. Only when the user is scrolling the page, not the carousel. There's a way to change the swipe sensivity? To avoid accidental scroll in the carousel when the user is scrolling the page.

Tks!

**Comment by snake-345** [comment]
Do you use last version of plugin? Sensitivity was changed at 0.3.2 version. If it's not enough, I can make it configurable, but I don't know when I can find time for that. Maybe if you can, try make it configurable and make pull request ;)

**Comment by diegosomar** [comment]
Great! I will try to make a configurable and submit a PR.
I think the sensivity is setted here, correct?
https://github.com/snake-345/jcarouselSwipe/blob/master/src/jquery.jcarousel-swipe.js#L73

`xDiff` must be bigger then 10 to slide, right?

Tks!

**Comment by snake-345** [comment]
Yep =)

**Comment by diegosomar** [comment]
Tks!
